[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "AkHAin2VBQpBdvQ46AmsHTZ17Z6JuaUQ3iFBd2Vda7Tm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
